Repository milieuinfo/webcomponent-vl-ui-link, pull requests merged in 2019-09, with the labels that each got.

#20 UIG-218
  vl-link.src.js
Labels: maintenance

#21 Update link naar demo
  vl-link.src.js
Labels: maintenance

#22 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#10 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#27 Update dependency vl-ui-icon to v2.0.11
  package-lock.json
  package.json
Labels: dependencies

#26 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#25 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#24 Update dependency @govflanders/vl-ui-link to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#23 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#29 Update package-lock en downgrade govflanders deps naar 3.7.2
  package-lock.json
  package.json
Labels: bug

#31 Update dependency vl-ui-icon to v2.0.12
  package-lock.json
  package.json
Labels: dependencies

#32 Automatic commit via update script
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
  style.css.map
Labels: maintenance

#36 UIG-143 - Update bamboo template
  package.json
Labels: maintenance

#37 Update vl-ui-util
  CODEOWNERS
  package-lock.json
  package.json
Labels: maintenance
