Repository milieuinfo/webcomponent-vl-ui-link, pull requests merged in 2020-01, with the labels that each got.

#48 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#50 Update util
  .gitignore
  package-lock.json
  package.json
  test/e2e/components/vl-link.js
Labels: bugfix

#52 packate-lock
  vl-link.js
Labels: bugfix

#57 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#55 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#56 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
Labels: maintenance

#58 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#59 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
